language: haskell

ghc:
  - 7.8
  - 7.6
  - 7.4

env:
  - SUBDIR=instances-case-insensitive
  - SUBDIR=instances-new-base
  - SUBDIR=instances-unordered-containers
  - SUBDIR=instances-vector

before_install:
  - cd "$SUBDIR"

script:
  - cabal configure && cabal build

  # Following line tests if sdist package is created correctly.
  - cabal sdist && cabal install dist/*.tar.gz
